# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
my_array = np.zeros(10)
my_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [7]:
my_array = np.arange(10,50)
my_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [8]:
my_array.shape

(40,)

5. Print the type of the previous array in question 3

In [23]:
print(my_array.dtype)

int32


6. Print the numpy version and the configuration


In [19]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [9]:
print(my_array.ndim)

1


8. Create a boolean array with all the True values

In [25]:
bol_array = np.ones((2, 2), dtype=bool)
bol_array

array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [28]:
d2_array = np.zeros((2,2))
d2_array

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [34]:
d3_array = np.zeros((2,2,3))
d3_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [24]:
print(f"1st method\n {np.flip(my_array, 0)}\n2nd method\n {my_array[::-1]}")

1st method
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
2nd method
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [35]:
null_array = np.zeros(10)
null_array[4] = 1
null_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [41]:
identity_array = np.identity(3)
identity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [43]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [43]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print(f"1st method\n {arr1*arr2} \n2nd method \n {np.multiply(arr1,arr2)}")

1st method
 [[ 0.  8.  3.]
 [28. 10. 72.]] 
2nd method 
 [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [7]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
compare = np.equal(arr1,arr2)
compare

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [9]:
arr = np.arange(10)
odd = arr[arr%2==1]
odd

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [11]:
odd_new = np.where(odd, -1, odd) 
odd_new

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [59]:
arr = np.arange(10)
arr[np.array([5,6,7,8])] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [12]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0 
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [95]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
print(arr2d)
arr2d[1,1] = 12
arr2d


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [13]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [64]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[0,:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [47]:
arr = np.arange(0,10).reshape(2,5)
print(arr)
arr[1,1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [48]:
arr = np.arange(0,10).reshape(2,5)
print(arr)
arr[:2,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [82]:
r_arr = np.random.random((10,10))
print(f"Max = {np.max(r_arr)}\nMin = {np.min(r_arr)}")

Max = 0.9821359742237662
Min = 0.04018161419763533


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [16]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.in1d(a, b)))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [113]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print("")
print(data[names != 'Will'])

[[ 0.42136841  1.25863411  0.34262893 -0.20096853]
 [ 0.03083813 -1.31637674  0.15825995  1.14204341]
 [-0.14358118 -1.53787999  0.61632538 -0.3171436 ]
 [ 1.62100579  1.5667008   0.20348549  0.40311329]
 [ 0.35153962  1.08316293 -0.51814962 -0.36989613]
 [ 2.75716767  0.37185748 -0.28962001 -0.23218181]
 [ 0.10027621  0.51557008  0.38332752  0.31418881]]

[[ 0.42136841  1.25863411  0.34262893 -0.20096853]
 [ 0.03083813 -1.31637674  0.15825995  1.14204341]
 [ 1.62100579  1.5667008   0.20348549  0.40311329]
 [ 2.75716767  0.37185748 -0.28962001 -0.23218181]
 [ 0.10027621  0.51557008  0.38332752  0.31418881]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print(" ")
print(data[~(names == 'Will') & ~(names =='Joe')])

[[-1.78569051  0.10324427  1.17215087 -1.36783552]
 [ 0.79647166 -0.67684566  0.83773238  0.23080492]
 [ 0.20819555 -0.39300694  0.8011355  -0.78472551]
 [ 0.77536966 -0.69870436 -1.36725424 -0.77909409]
 [ 0.09634723  1.92553876 -0.92239564  0.74781341]
 [-1.39656585  1.02255314  0.46378071  0.46621601]
 [ 0.5464443   1.51100672 -0.04949805 -0.38336335]]
 
[[-1.78569051  0.10324427  1.17215087 -1.36783552]
 [ 0.77536966 -0.69870436 -1.36725424 -0.77909409]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [36]:
arr = np.arange(1,16, dtype = np.float).reshape((5,3))
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [2]:
arr = np.arange(1,17, dtype = np.float).reshape((2,2,4))
arr

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [4]:
print(arr.T)

[[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [79]:
arr = np.random.rand(10)
arr_sqrt = np.sqrt(arr)
print(arr_sqrt)
arr_new = np.where(arr_sqrt<0.5,0,arr_sqrt)
arr_new

[0.83177294 0.95181371 0.84252024 0.71489508 0.81319961 0.32056918
 0.80704149 0.415827   0.75653902 0.9910067 ]


array([0.83177294, 0.95181371, 0.84252024, 0.71489508, 0.81319961,
       0.        , 0.80704149, 0.        , 0.75653902, 0.9910067 ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [99]:
arr1 = np.random.random(12)
print(f"{arr1}\n")
arr2 = np.random.random(12)
print(arr2)
arr3 = np.maximum(arr1,arr2)
arr3

[0.5988738  0.19129678 0.86870502 0.57776203 0.23464902 0.7252711
 0.31077295 0.0956218  0.68743708 0.99539175 0.48797953 0.85981032]

[0.17572653 0.19084993 0.72475569 0.25523735 0.84572718 0.54498904
 0.22713417 0.58137409 0.3473256  0.40068393 0.29700259 0.18433979]


array([0.5988738 , 0.19129678, 0.86870502, 0.57776203, 0.84572718,
       0.7252711 , 0.31077295, 0.58137409, 0.68743708, 0.99539175,
       0.48797953, 0.85981032])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [108]:
names = np.array(['Tob', 'Joe', 'Will', 'Rob', 'Will', 'Joe', 'Joe'])
unique = np.unique(names)
print(unique)

['Joe' 'Rob' 'Tob' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [124]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a, b)
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [136]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray,1,1)
sampleArray = np.insert(sampleArray,1,newColumn,1)
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [138]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [139]:
arr = np.random.random(20)
cum_sum = np.cumsum(arr)
cum_sum

array([ 0.96730802,  1.82686531,  2.79686365,  3.68254984,  4.47754594,
        5.05717451,  5.96328293,  6.19627745,  7.04125541,  7.93222084,
        8.10903769,  9.01803517,  9.45728205, 10.2729209 , 10.52107837,
       11.39232906, 11.41057493, 11.83816882, 12.2133774 , 12.99178173])